// This is a sample test file for the LightSm state machine.
// Generated by StateSmith.
// Feel free to make a copy and start adding your own tests.

// This sample uses CppUTest to run tests. 
//
// To run the tests:
// - install CppUTest if you don't already have it (https://cpputest.github.io/)
// - make a copy of this file, eg. LightSm.test.c
// - mock any dependencies from your state machine (see below)
// - compile your state machine and tests, eg.
//   g++ LightSm.test.c LightSm.c -L/path/to/CppUTest/lib/dir -lCppUTest
// - make the tests executable, eg.
//   chmod +x a.out
// - run the tests, eg.
//   ./a.out

#include "CppUTest/CommandLineTestRunner.h"

// ACTION REQUIRED
// You must define any actions and variables used by your state machine.
// We recommend mocking rather than importing your actual functions,
// to keep these tests purely about testing the state machine itself.
// (Your function implementations should also be tested, but in separate tests.)
// Create LightSm.mocks.test.h and add your mocks there.
#include "LightSm.mocks.test.h"

#include "LightSm.h"




int main(int ac, char** av)
{
    return CommandLineTestRunner::RunAllTests(ac, av);
}


// Use 'state_id' to access the current state of the state machine, eg.
// CHECK_EQUAL(LightSm_StateId_OFF, sm.state_id);
//
// Use 'vars' to access the variables of the state machine, eg.
// CHECK_EQUAL(sm->vars.myVar, 42);
//
// Use 'dispatch_event' to send events to the state machine, eg.
// LightSm_dispatch_event(LightSm_EventId_INCREASE, &sm);
//
// Use mock functions to check if the functions are called, eg.
// mock().expectOneCall("println");
// See https://cpputest.github.io/ for more information on CppUTest.

TEST_GROUP(LightSmTest)
{
};

TEST(LightSmTest, StartsInOffState) {
    LightSm sm;
    LightSm_ctor(&sm);
    LightSm_start(&sm);
    CHECK_EQUAL(LightSm_StateId_OFF, sm.state_id);
}
