// This is a sample test file for the LightSm state machine.
// Generated by StateSmith.
// Feel free to make a copy and start adding your own tests.

// This sample uses npm and jest to run tests. 
//
// To setup tests:
// - install npm if you don't already have it (https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)
// - Install the jest dev dependency: `npm install --save-dev jest`
// - edit your package.json file, see package.sample.json for an example
//   (Jest needs some light setup to work with ES6 modules for 'import' and 'export')
//
// To run, type `npm test` in the terminal

#include "CppUTest/TestHarness.h"
#include "CppUTest/CommandLineTestRunner.h"

// ACTION REQUIRED
// You must define any actions and variables used by your state machine.
// We recommend mocking rather than importing your actual functions,
// to keep these tests purely about testing the state machine itself.
// (Your function implementations should also be tested, but in separate tests.)
// Create LightSm.mocks.test.h and add your mocks there.
#include "LightSm.mocks.test.h"

#include "LightSm.h"




int main(int ac, char** av)
{
    return CommandLineTestRunner::RunAllTests(ac, av);
}


// Use 'state_id' to access the current state of the state machine, eg.
// expect(sm.state_id).toBe(LightSm.StateId.OFF);
//
// Use 'vars' to access the variables of the state machine, eg.
// expect(sm.vars.myVar).toBe(42);
//
// Use 'dispatchEvent' to send events to the state machine, eg.
// sm.dispatchEvent(LightSm.EventId.INCREASE);
//
// Use mock functions to check if the functions are called, eg.
// expect(globalThis.println.mock.calls).toHaveLength(1);
// See https://jestjs.io/ for more information on Jest.

TEST_GROUP(LightSmTest)
{
};

TEST(LightSmTest, StartsInOffState) {
    LightSm sm;
    LightSm_ctor(&sm);
    LightSm_start(&sm);
    CHECK_EQUAL(LightSm_StateId::LightSm_StateId_OFF, sm.state_id);
}
